### ISSUE TITLE
no mouse movement.

### ISSUE THREAD

**Issue by ipatch** [SipRadius/Qemu-USB-Tablet-Driver#1]
I wasn't able to move the mouse after installing this driver, from the git source.  I am presently running 10.10.2

**Comment by funman** [comment]
What is your Qemu command line?

Do you use -usbdevice tablet ?

**Comment by ipatch** [comment]
Yes I tried `-usbdevice tablet`.  I'm using `QEMU emulator version 2.2.50, Copyright (c) 2003-2008 Fabrice Bellard` compiled from the git source.

**Comment by funman** [comment]
Ok can you give the qemu git hash and **full** command line?

**Comment by ipatch** [comment]
Yeah, the full command line, `qemu-system-x86_64 -enable-kvm -m 4096 -cpu core2duo -machine q35 -usb -device usb-kbd -usbdevice tablet -device isa-applesmc,osk="key" -kernel VM/chameleon_svn2593_boot -smbios type=2 -device ide-drive,bus=ide.2,drive=MacHDD -drive id=MacHDD,if=none,file=VM/osx-yosemite.img -netdev user,id=hub0port0 -device e1000-82545em,netdev=hub0port0,id=mac_vnet0 -monitor stdio -vga qxl`

As for the qemu git hash, I'll have to get back to you for that one, as I don't know how to obtain that right now.

**Comment by funman** [comment]
Closed by #2
